version: '3.7'

services:
  web:
    build: ./history
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./history/:/usr/src/history/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=history

volumes:
  postgres_data: