# Generated by Django 3.1.5 on 2021-01-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_main', '0004_mainuser_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='email_is_hiden',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='phone_is_hiden',
            field=models.BooleanField(default=True),
        ),
    ]
