# Generated by Django 3.1.5 on 2021-01-28 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history_main', '0005_auto_20210128_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainuser',
            old_name='email_is_hiden',
            new_name='email_is_hidden',
        ),
        migrations.RenameField(
            model_name='mainuser',
            old_name='phone_is_hiden',
            new_name='phone_is_hidden',
        ),
    ]
