# Generated by Django 3.1.5 on 2021-01-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_main', '0007_auto_20210129_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='avatar',
            field=models.ImageField(default='user_avatars/default.png', upload_to='user_avatars/'),
        ),
    ]
