# Generated by Django 3.1.5 on 2021-02-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_main', '0009_mainuser_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='image',
            field=models.FileField(upload_to='museum_photos'),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='avatar',
            field=models.FileField(default='user_avatars/default.png', upload_to='user_avatars/'),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='secret_key',
            field=models.CharField(default='WYikWjDHLwARmAGGaCAE', max_length=20),
        ),
        migrations.AlterField(
            model_name='solderpost',
            name='photo',
            field=models.FileField(upload_to='solder_photos/'),
        ),
    ]
