# Generated by Django 3.1.5 on 2021-03-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_main', '0010_auto_20210206_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=150, verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Плохое слово',
                'verbose_name_plural': 'Плохие слова',
            },
        ),
    ]
