# Generated by Django 3.1.5 on 2021-02-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_main', '0010_auto_20210206_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='secret_key',
            field=models.CharField(default='PsCRUOzFyXcLLsEltjcg', max_length=20),
        ),
    ]
