# Generated by Django 3.1.5 on 2021-01-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solderpost',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
