# Generated by Django 3.1.5 on 2021-01-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_main', '0003_auto_20210126_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
